/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as PatternsPatternSetIdRouteImport } from './routes/patterns.$patternSetId'

const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => RunsRoute,
} as any)
const PatternsPatternSetIdRoute = PatternsPatternSetIdRouteImport.update({
  id: '/$patternSetId',
  path: '/$patternSetId',
  getParentRoute: () => PatternsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/patterns': typeof PatternsRouteWithChildren
  '/runs': typeof RunsRouteWithChildren
  '/strategies': typeof StrategiesRoute
  '/patterns/$patternSetId': typeof PatternsPatternSetIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/patterns': typeof PatternsRouteWithChildren
  '/runs': typeof RunsRouteWithChildren
  '/strategies': typeof StrategiesRoute
  '/patterns/$patternSetId': typeof PatternsPatternSetIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/patterns': typeof PatternsRouteWithChildren
  '/runs': typeof RunsRouteWithChildren
  '/strategies': typeof StrategiesRoute
  '/patterns/$patternSetId': typeof PatternsPatternSetIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/patterns'
    | '/runs'
    | '/strategies'
    | '/patterns/$patternSetId'
    | '/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/patterns'
    | '/runs'
    | '/strategies'
    | '/patterns/$patternSetId'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/patterns'
    | '/runs'
    | '/strategies'
    | '/patterns/$patternSetId'
    | '/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  PatternsRoute: typeof PatternsRouteWithChildren
  RunsRoute: typeof RunsRouteWithChildren
  StrategiesRoute: typeof StrategiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof RunsRoute
    }
    '/patterns/$patternSetId': {
      id: '/patterns/$patternSetId'
      path: '/$patternSetId'
      fullPath: '/patterns/$patternSetId'
      preLoaderRoute: typeof PatternsPatternSetIdRouteImport
      parentRoute: typeof PatternsRoute
    }
  }
}

interface PatternsRouteChildren {
  PatternsPatternSetIdRoute: typeof PatternsPatternSetIdRoute
}

const PatternsRouteChildren: PatternsRouteChildren = {
  PatternsPatternSetIdRoute: PatternsPatternSetIdRoute,
}

const PatternsRouteWithChildren = PatternsRoute._addFileChildren(
  PatternsRouteChildren,
)

interface RunsRouteChildren {
  RunsRunIdRoute: typeof RunsRunIdRoute
}

const RunsRouteChildren: RunsRouteChildren = {
  RunsRunIdRoute: RunsRunIdRoute,
}

const RunsRouteWithChildren = RunsRoute._addFileChildren(RunsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  PatternsRoute: PatternsRouteWithChildren,
  RunsRoute: RunsRouteWithChildren,
  StrategiesRoute: StrategiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
